function plotfits(fitnplt, settings)
% names is a cell array containing headers for plots
% data is a cell vector containing (x,y,err) triplets (col vectors)
% fits is a cell vector containing the cfit objects for data

pltCount= max(fitnplt.plotGroup);
division = [4,3];
questions = {sprintf(['There are %d plots to draw.\n\n',...
                      'Number of lines per page'],pltCount),...
                      'Number of plots per line'};
answer= inputdlg(questions,'Layout',1,{'4','3'});
if ~isempty(answer)
    answer = (cellfun(@str2double,answer))';
    answer(~isfinite(answer)) = division(~isfinite(answer));
    division = answer;

    % close any pre-existing plot windows generated by this code
    close(findobj('tag','batchfitplot'));
    setPlotVisuals(settings);    % -- Visual defaults
    drawPlotPage(fitnplt,settings,division);
end
end